### ISSUE TITLE
Error on loading the plugin in atom

### ISSUE THREAD

**Issue by vinif** [orktes/atom-react#100]
[Enter steps to reproduce below:]

1. Installed the package

**Atom Version**: 1.0.19
**System**: elementary OS
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.12.10

### Stack Trace

Failed to load the react package

```
At object is not a function

TypeError: object is not a function
  at Object.<anonymous> (/home/vini/.atom/packages/react/index.coffee:3:18)
  at Object.<anonymous> (/home/vini/.atom/packages/react/index.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:761:34)
  at /usr/share/atom/resources/app.asar/src/package.js:192:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:169:15)
  at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:183:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:485:30)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "react": {}
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.6.0
cucumber, v0.5.0
file-icons, v1.6.9
git-hide, v0.1.2
language-babel, v0.15.4
linter, v1.6.0
linter-flow-plus, v3.1.0
linter-js-yaml, v1.1.2
minimap, v4.13.4
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-linter, v1.0.0
react, v0.12.10
react-snippets, v0.2.0
redux-snippets, v0.2.1
refactor, v0.6.0
tree-view-git-status, v0.2.2

# Dev
No dev packages
```

**Comment by orktes** [comment]
Seems to be more related to atom than the plugin. Have you tried reinstalling?
