### ISSUE TITLE
Install error: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by kenhoff** [orktes/atom-react#112]
Hey there - I'm getting an error when running `apm stars --install`. See the output below.

```
Installing react to C:\Users\kenhoff\.atom\packages failed

npm WARN addRemoteGit Error: Command failed:
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\kenhoff\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\kenhoff\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\kenhoff\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: Cloning into bare repository 'C:\Users\kenhoff\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! git clone --template=C:\Users\kenhoff\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\kenhoff\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\kenhoff\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\kenhoff\\AppData\\Local\\atom\\app-1.1.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\kenhoff\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\kenhoff\\.atom\\.apmrc" "install" "C:\\Users\\kenhoff\\AppData\\Local\\Temp\\d-115103-1056-m8qzxp\\package.tgz" "--target=0.30.7" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\kenhoff\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Any thoughts? Thanks!

**Comment by kenhoff** [comment]
Recently did a complete OS (Win 10) wipe and re-image; not getting this issue any more. Not sure what was going on.
