### ISSUE TITLE
Update fails on Windows

### ISSUE THREAD

**Issue by martynhoyer** [orktes/atom-react#155]
I'd imagine this is probably a Windows thing, it usually is!

Looks like it might not actually be directly related to this repo, but I thought I'd better raise it!

```
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\[redacted]\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\[redacted]\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\[redacted]\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: Cloning into bare repository 'C:\Users\[redacted]\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! git clone --template=C:\Users\[redacted]\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\[redacted]\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\[redacted]\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\[redacted]\\AppData\\Local\\atom\\app-1.6.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\[redacted]\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\[redacted]\\.atom\\.apmrc" "install" "C:\\Users\\[redacted]\\AppData\\Local\\Temp\\d-11636-7268-4rf7t7\\package.tgz" "--target=0.34.5" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\[redacted]\.atom\.apm\_git-remotes\https-github-com-millermedeiros-rocambole-git-fa28ae6f'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by Ulthes** [comment]
I had the same problem. However installing through cmd helped. Try running `apm install react` in your Commandline Prompt.

**Comment by jonathandelgado** [comment]
I just ran into this, command line also had the issue. I was running git `2.8.2` on windows, an update to `2.9.2` resolved this issue for me.
