### ISSUE TITLE
Crash on text entry with 0.8.5

### ISSUE THREAD

**Issue by clloyd** [orktes/atom-react#20]
Current affecting all my JSX files. Typing or pasting gives the following error:

Uncaught TypeError: Cannot read property 'testSync' of undefined
/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124
Hide Stack Trace
TypeError: Cannot read property 'testSync' of undefined
  at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/Users/chris/.atom/packages/react/index.coffee:63:35)
  at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:374:26)
  at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRow] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:472:21)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:809:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1178:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:802:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:767:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:786:19)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:582:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:297:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1178:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:296:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

Disabling the React package fixes the issue.

**Comment by Calyhre** [comment]
Same here with `0.8.4` and latest Atom `0.172.0`.
Updating to `0.8.5` did not help.

**Comment by orktes** [comment]
Just did huge refactor on that part. Trying to fix asap!

**Comment by orktes** [comment]
Have you tried restarting you editor?

**Comment by clloyd** [comment]
I've restarted my editor and also tried re-installing the package and updating atom to 0.172.0.

**Comment by orktes** [comment]
I was able to reproduce. Hold on! :)

**Comment by orktes** [comment]
Should be resolved now! 0.8.6 published.

**Comment by clloyd** [comment]
Yep fixed for me with 0.8.6! Thanks for the quick response!

**Comment by Calyhre** [comment]
Fixed. :+1:

**Comment by orktes** [comment]
Thanks for informing! I apparently were too quick in fixing windows related issues and caused other problems :P Thanks for you patience.
