### ISSUE TITLE
Uncaught TypeError: this.getRegexForProperty is not a function

### ISSUE THREAD

**Issue by JaneCoder** [orktes/atom-react#203]
This just suddenly happened after a morning of working on react code with no issues. 
I reverted my code to an earlier state with git, tried closing and reopening atom, and restarting my computer. My react version is 15.0.1.

Here is the complete error:

/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.autoDecreaseIndentForBufferRow (/Users/klc34/.atom/packages/react/lib/atom-react.coffee:47:38)
    at TextEditor.module.exports.TextEditor.autoDecreaseIndentForBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3558:32)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:499:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1063:29
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1102:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1096:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2497:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2459:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1094:19)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1060:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:482:26)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:61)

**Comment by JaneCoder** [comment]
Sorry, did not realize I need to update to 0.16.x

**Comment by devdlx** [comment]
same issue with 0.16.1. reinstalled, same issue

**Comment by fxalvarezd** [comment]
Updated to 0.16.1 and still get the error, out of the blue...

**Comment by danielpape** [comment]
Updates to 0.16.1 and getting this error too.

**Comment by chammonsvusion** [comment]
Updated to 0.16.1 .. after restart atom error went away.

**Comment by Zevgon** [comment]
I skirted around the problem by disabling the react package and installing language-babel 2.44.1

**Comment by bocharovn** [comment]
I've updated all the packages, restarted .. no change. Then I've restarted it agin but when noticed an anoying tab asking if I want to help to improove Atom which i previusly ignored; I clicked Yes and Crazy! - got it to work!! 
Well not saying clicking on Yes fixed it.. maybe , maybe not! Just if anyone in the same situation try it.

**Comment by gergob** [comment]
for me, the:

> Updated to 0.16.1 .. after restart atom error went away.

also worked. Thanks for the hints @chammonsvusion

**Comment by jason-collier** [comment]
I had the same issue. Started after a `git reset --hard` on a project listed in the tree view. To fix, I opened a new Atom window, closed the old window, and added the projects to the tree view.

**Comment by xuan9230** [comment]
Updating to 0.16.1 can fix the issue though, I'm very confused - why I need this update all of a sudden? Could still work yesterday and made no change since then..

**Comment by shikelong** [comment]
Updating to 0.16.1 and restart Atom can fix the bug.

**Comment by sumanthcn** [comment]
I had a smae issue and I have Updated to 0.16.1 and restart Atom. This has been fixed now.

**Comment by fengerzh** [comment]
Yes, you MUST restart Atom, even after upgrade to 0.16.1.

**Comment by foodaka** [comment]
I have restarted atom and still have the issue

**Comment by sumanthcn** [comment]
@fengerzh if your using react snippets, please update it to latest version. This also could be a reason why its not working.

**Comment by AdamBCo** [comment]
Still having issues

**Comment by lordKnighton** [comment]
😸 I was having issues as well, but went away after upgrading & close & restart atom. ✅

**Comment by ty4z2008** [comment]
I have also encountered this  error message . when i upgrade rect package version to 0.16.1  . it's not reappear

**Comment by parthrao** [comment]
After upgrading all packages and restarting the atom problem went away.

**Comment by BrandTurner** [comment]
Another user confirming that updating to v 16.1 and restarting Atom solves this issue. You can close this one now :)

**Comment by anas10** [comment]
Same here the update to v16.1 + restart solved the issue.

**Comment by bboysathish** [comment]
Same here the update to v16.1 + restart solved the issue.

**Comment by shieldstyler** [comment]
In case it wasn't obvious, from Atom, go to File > Settings and then click Packages and update react

**Comment by ashwinpreet** [comment]
Updating the React package to v0.16.1 and restarting the Atom editor solved for me.
