### ISSUE TITLE
"Uncaught TypeError: this.getRegexForProperty is not a function" error after selecting 'auto indent'

### ISSUE THREAD

**Issue by avivr** [orktes/atom-react#208]
Steps to reproduce

1. Select 'Auto indent' from the command palette 

![screen shot 2016-10-26 at 14 49 29](https://cloud.githubusercontent.com/assets/7034094/19724931/86cf5d60-9b8b-11e6-9fb8-e5e85d885f40.png)

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.16.1

### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/Users/aviv/.atom/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:366:26)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRows (/Applications/Atom.app/Contents/Resources/app.asar/src/language-mode.js:360:14)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRows (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3554:32)
    at Selection.module.exports.Selection.autoIndentSelectedRows (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:679:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2772:26
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1102:29
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1096:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2493:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2459:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1094:19)
    at TextEditor.module.exports.TextEditor.autoIndentSelectedRows (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2771:19)
    at TextEditor.commandRegistry.add.stopEventPropagationAndGroupUndo.editor:auto-indent (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:592:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:661:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1519:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:660:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:20.7.0 atom-beautify:beautify-editor (atom-text-editor.editor)
     -1:18.2.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:17 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -1:12.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:12.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:11.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:10 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:10 editor:auto-indent (atom-text-editor.editor)
     -0:35.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:31.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:31.4.0 editor:auto-indent (atom-text-editor.editor)
     -0:18.5.0 core:cancel (a.stack-toggle)
     -0:03.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 editor:auto-indent (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (active)
atom-beautify, v0.29.13 (active)
atom-ternjs, v0.15.0 (active)
atom-typescript, v10.1.9 (active)
autoclose-html, v0.23.0 (active)
autocomplete-modules, v1.6.7 (active)
color-picker, v2.2.2 (active)
double-tag, v0.4.0 (active)
file-icons, v1.7.22 (active)
goto, v1.7.1 (inactive)
hyperclick, v0.0.39 (active)
js-hyperclick, v1.9.0 (active)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
markdown-scroll-sync, v2.1.2 (active)
pigments, v0.37.0 (active)
react, v0.16.1 (active)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by mitsuishihidemi** [comment]
how can I resolve it?

**Comment by vinay3206** [comment]
I am also facing same!

**Comment by vinay3206** [comment]
ok got it. Toggle:Auto indent will set it off 👍

**Comment by dolfelt** [comment]
I'm having this issue as well.

**Comment by avivr** [comment]
Was solved for me after updating to latest version, closing all atom windows and reopening

**Comment by dolfelt** [comment]
Me too, thanks!

**Comment by yagudaev** [comment]
Having this issue too. ` 1.11.2` is the latest version of atom. @avivr what did you update?

**Comment by spandzgit** [comment]
apm update react

solves it..

**Comment by tuanh118** [comment]
Having this issue with atom-beta. Only .jsx files cannot be edited.
Atom version: 1.13.0-beta3
OS: Ubuntu 16.04

**Comment by timrichd** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Ubuntu 16.04.1
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.16.0


### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/home/tim/.atom/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/usr/share/atom/resources/app.asar/src/language-mode.js:372:26)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/usr/share/atom/resources/app.asar/src/text-editor.js:3554:32)
    at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app.asar/src/selection.js:494:21)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1068:29
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1107:28
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1524:26)
    at /usr/share/atom/resources/app.asar/src/text-editor.js:1101:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2502:18)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:2464:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:1099:19)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app.asar/src/text-editor.js:1065:19)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.module.exports.TextEditor.insertNewline (/usr/share/atom/resources/app.asar/src/text-editor.js:1080:19)
    at TextEditor.object.(anonymous function) [as insertNewline] (/usr/share/atom/resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditor.editor:newline (/usr/share/atom/resources/app.asar/src/register-default-commands.js:603:21)
    at /usr/share/atom/resources/app.asar/src/register-default-commands.js:663:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1524:26)
    at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/register-default-commands.js:662:22)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
 16x -4:59.3.0 core:close (atom-text-editor.editor.is-focused)
     -4:51.6.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-monokai.theme-atom-dark-ui)
     -4:47.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:57.5.0 tree-view:reveal-active-file (div.title)
  2x -3:28.8.0 core:copy (atom-text-editor.editor.is-focused)
  4x -2:47.7.0 git-blame:toggle (atom-text-editor.editor.is-focused)
     -1:54.3.0 delete-lines:toggle (atom-text-editor.editor.is-focused)
     -1:52.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:49.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:49.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:37.2.0 pane:split-right-and-copy-active-item (atom-text-editor.editor.is-focused)
     -0:00.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
delete-lines, v0.4.17 (active)
fonts, v1.7.0 (active)
git-blame, v0.4.11 (active)
js-hyperclick, v1.9.0 (active)
language-docker, v1.1.7 (active)
language-perl, v0.37.0 (active)
language-perl-template-toolkit, v0.1.0 (active)
letter-spacing, v0.3.1 (active)
line-diff-details, v1.4.0 (active)
linter, v1.11.18 (active)
linter-eslint, v7.2.3 (active)
linter-perl, v0.8.0 (active)
linter-perlcritic, v1.2.3 (active)
linter-stylelint, v3.6.0 (active)
minimap, v4.25.6 (active)
minimap-git-diff, v4.3.1 (active)
minimap-highlight-selected, v4.4.0 (active)
minimap-linter, v1.6.0 (active)
monokai, v0.18.0 (active)
perltidy, v3.0.0 (active)
pretty-json, v1.6.1 (active)
react, v0.16.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.1 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (active)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by timrichd** [comment]
updated react and it works

**Comment by eos87** [comment]
I'm having the same issue

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.11.6
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.16.0


### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:871

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.autoDecreaseIndentForBufferRow (/Users/eos87/.atom/packages/react/lib/atom-react.coffee:47:38)
    at TextEditor.module.exports.TextEditor.autoDecreaseIndentForBufferRow (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:3562:32)
    at Selection.module.exports.Selection.insertText (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/selection.js:499:21)
    at /Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1068:29
    at /Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1107:28
    at TextBuffer.module.exports.TextBuffer.transact (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:18)
    at TextEditor.module.exports.TextEditor.transact (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1524:26)
    at /Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1101:24
    at TextEditor.module.exports.TextEditor.mergeSelections (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2498:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2464:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1099:19)
    at TextEditor.module.exports.TextEditor.insertText (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1065:19)
    at TextEditor.object.(anonymous function) [as insertText] (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:479:26)
    at HTMLDivElement.<anonymous> (/Users/eos87/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:3:59)
```

### Commands

```
     -1:26.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:26.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:09.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:08.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:07.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:07.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:06.5.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:04.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:03.8.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:03.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:03.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:03.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:01.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:59.9.0 core:move-to-top (atom-text-editor.editor.is-focused)
  4x -0:59.2.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:58.2.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.pyc"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-spacegray"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.11 (inactive)
atom-django, v0.3.2 (active)
atom-jade, v0.3.0 (active)
autocomplete-python, v1.8.20 (active)
base16-ocean-dark-spacegray, v0.12.0 (active)
base16-ocean-dark-syntax-theme, v0.1.9 (inactive)
color-picker, v2.2.2 (active)
highlight-selected, v0.11.2 (active)
language-pug, v0.0.19 (active)
linter, v1.11.18 (active)
linter-flake8, v2.1.3 (active)
react, v0.16.0 (active)
snippet-generator, v0.3.2 (inactive)
Stylus, v3.1.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by michaelbrazell** [comment]
Same issue, back again after a few days.  Updating the React plugin didn't seem to help this time.

**Comment by matthewberkompas** [comment]
For anyone else with this problem, @michaelbrazell's solution seems to fix the problem. Thanks for posting!

**Comment by ivarrian** [comment]
`apm update react` did the trick for me.

**Comment by NorviNS** [comment]
`apm update react` fixed it

**Comment by dleal3** [comment]
@michaelbrazell Followed your steps and fixed the issue! I was going crazy over here, thanks brother for posting!

**Comment by drbortel** [comment]
when I try to install or update react, I get this error:

npm ERR! git fetch -a origin (https://github.com/millermedeiros/rocambole.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.1.7601

<snip>

npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true fetch -a origin
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!

Any idea what causes this ?

**Comment by midgethoen** [comment]
im still having this issue in both 0.16.0 & 0.17.0
