### ISSUE TITLE
I Can't install plugin in atom

### ISSUE THREAD

**Issue by fjballesteros** [orktes/atom-react#227]
This is the Log:

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:213:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:827:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 because of error: { [Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\T0\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: Cloning into bare repository 'C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85'...
npm ERR! git clone --template=C:\Users\T0\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Recv failure: Connection was reset
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\T0\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\T0\\AppData\\Local\\atom\\app-1.15.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\T0\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\T0\\.atom\\.apmrc" "install" "C:\\Users\\T0\\AppData\\Local\\Temp\\d-117228-10648-9xauku\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\T0\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85
npm ERR! Cloning into bare repository 'C:\Users\T0\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85'...
npm ERR! fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Recv failure: Connection was reset
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\T0\AppData\Local\Temp\apm-install-dir-117228-10648-rjtbro\npm-debug.log

Thanks.

**Comment by Alejandro04** [comment]
I have this problem too

**Comment by leedo1982** [comment]
I have this problem.....too.....

**Comment by caleem** [comment]
Any ETA on this issue ?

**Comment by MatcheranyZ** [comment]
I have this problem.....too.....
