### ISSUE TITLE
Cannot read property 'openScopes' of undefined

### ISSUE THREAD

**Issue by danqing** [orktes/atom-react#235]
Atom 1.19b4, macOS 10.12.6:

```
TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at /Applications/Atom Beta.app/Contents/Resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:3388:33)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom Beta.app/Contents/Resources/app/src/tokenized-buffer.js:143:33)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2942:41)
    at AtomReact.autoSetGrammar (/Users/dliu/.atom/packages/react/lib/atom-react.coffee:131:14)
    at AtomReact.processEditor (/Users/dliu/.atom/packages/react/lib/atom-react.coffee:309:6)
    at Workspace.observeTextEditors (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:717:15)
    at AtomReact.activate (/Users/dliu/.atom/packages/react/lib/atom-react.coffee:330:46)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom Beta.app/Contents/Resources/app/src/package-manager.js:603:52)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:843:36
```

**Comment by orktes** [comment]
Thanks for reporting!

**Comment by SetCodesToFire** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [bracket-matcher](https://github.com/atom/bracket-matcher) package 0.86.0


### Stack Trace

Uncaught TypeError: Cannot read property 'openScopes' of undefined

```
At C:\Users\setCodesToFire\AppData\Local\atom\app-1.19.0\resources\app\node_modules\bracket-matcher\lib\tag-finder.js:55

TypeError: Cannot read property 'openScopes' of undefined
    at TagFinder.module.exports.TagFinder.scopesForPositionMatchRegex (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:55:28)
    at TagFinder.module.exports.TagFinder.isCursorOnTag (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:45:25)
    at TagFinder.module.exports.TagFinder.findMatchingTags (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/tag-finder.js:174:22)
    at BracketMatcherView.module.exports.BracketMatcherView.updateMatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:128:41)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/bracket-matcher/lib/bracket-matcher-view.js:3:65
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TokenizedBuffer.module.exports.TokenizedBuffer.markTokenizationComplete (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:252:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:246:27)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/tokenized-buffer.js:206:32
    at ~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
  5x -4:21.1.0 core:backspace (input.hidden-input)
     -4:14 core:save (input.hidden-input)
     -1:55.9.0 editor:newline (input.hidden-input)
     -1:54.7.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```

```
