### ISSUE TITLE
error installing package

### ISSUE THREAD

**Issue by MichaelGreisberger** [orktes/atom-react#240]
hey everyone,
i have problems installing the package. 
I am getting the following error:
C:\Users\xxx>apm install react
Installing react to C:\Users\xxx\.atom\packages failed

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\xxx\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-g
it-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:334:11)
npm WARN addRemoteGit     at emitOne (events.js:96:13)
npm WARN addRemoteGit     at Socket.emit (events.js:188:7)
npm WARN addRemoteGit     at Pipe._handle.close [as _onclose] (net.js:498:12)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\xxx\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\xxx\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocamb
ole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: Cloning into bare repository 'C:\Users\xxx\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-
af4fdf85'...
npm ERR! git clone --template=C:\Users\xxx\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\xxx\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocamb
ole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Unknown SSL protocol error in connection to github.com:443
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.19.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\xxx\\AppData\\Local\\atom\\app-1.19.5\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--gl
obalconfig" "C:\\Users\\xxx\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\xxx\\.atom\\.apmrc" "install" "C:\\Users\\xxx\\AppData\\Local\\Temp\\d-11781-1552-bsetea.w48jpds4i\\package.tgz" "--runtime=electron"
"--target=1.6.9" "--arch=x64" "--global-style" "--msvs_version=2015"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\xxx\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\xxx\.atom\.apm\_git-remotes\git
-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85
npm ERR! Cloning into bare repository 'C:\Users\xxx\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85'...
npm ERR! fatal: unable to access 'https://github.com/millermedeiros/rocambole.git/': Unknown SSL protocol error in connection to github.com:443
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\AppData\Local\Temp\apm-install-dir-11781-1552-1b61gi8.8u0afw29\npm-debug.log

unfortunately the file it wants me to include here doesnt exist.. 
installing other packages worked just fine.

I am using Windows 10 on a 64bit machine 
i am behind a proxy but this shouldnt be any problem since installing other packages works fine.

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python
git 2.10.2.windows.
Atom 1.19.5

**Comment by PBscoots** [comment]
I nearly the same error output. I am behind a proxy too. I have the proxy settings in .amprc set, and can install other packages, but this one is the only one that I have found that fails. 
It gives me some 407 errors after proxy connect, which usually means bad proxy config, but that just doesn't make sense, because other packages all install fine with current settings.

**Comment by PBscoots** [comment]
I might have just found the fix, for me at least. my git config file also needed the proxy settings along with .apmrc. I have git installed direct, so the path to the file is c:/programdata/git, 
I had github desktop, git, AND the git package from cygwn installed, so I had no idea which configs to change. I uninstalled everything and started fresh with only git, and then atom. Uninstalling is pretty manual and annoying if you try it. Files flying everywhere that the uninstaller doesn't get

**Comment by KeitIG** [comment]
The package is not even findable on react packages page, I have no idea what is going on :(

**Comment by Gaurav70042** [comment]
![screenshot 10](https://user-images.githubusercontent.com/31271789/38025411-e87166be-32a5-11e8-8505-ffead6537c16.png)
#

**Comment by Gaurav70042** [comment]
its showing errors .........!   
while installing packages

**Comment by KeitIG** [comment]
You can try [language-babel](https://atom.io/packages/language-babel) if you want a more up-to-date alternative.
