### ISSUE TITLE
Failed to activate the react package

### ISSUE THREAD

**Issue by drstonebraker** [orktes/atom-react#248]
getting this error as soon as I open Atom:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.16.3

### Stack Trace

Failed to activate the react package

```
At Cannot read property 'jsxPatch' of undefined

TypeError: Cannot read property 'jsxPatch' of undefined
    at AtomReact.patchEditorLangModeAutoDecreaseIndentForBufferRow (/packages/react/lib/atom-react.coffee:45:17)
    at AtomReact.patchEditorLangMode (/packages/react/lib/atom-react.coffee:111:73)
    at AtomReact.processEditor (/packages/react/lib/atom-react.coffee:321:6)
    at Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:725:15)
    at AtomReact.activate (/packages/react/lib/atom-react.coffee:343:46)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:646:50)
    at /Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
atom-ternjs 0.18.3 
autoprefixer 3.7.1 
busy-signal 1.4.3 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.1 
linter 2.2.0 
linter-csslint 2.0.0 
linter-eslint 8.4.0 
linter-rubocop 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
react 0.16.3 
rspec 0.4.0 
vim-mode-plus 1.16.0 
```

**Comment by dmongeau** [comment]
You can disable the plugin and use https://atom.io/packages/language-javascript-jsx otherwise it's impossible to edit a jsx file.

**Comment by h8rry** [comment]
Can revert to the previous version for now `apm install react@0.16.2`

**Comment by shuaibird** [comment]
@h8rry rolling back still doesn't work for me

**Comment by sanzstez** [comment]
+1 have same issue

**Comment by dklanac** [comment]
+1 rollback and restart does not resolve the error.

**Comment by jnrepo** [comment]
what's the correct version to roll back to?

**Comment by dead** [comment]
You guys can patch locally by replacing the file in `.atom/packages/react/lib/atom-react.coffee` [with this](https://github.com/dead/atom-react/blob/228924e0dc20b2b7f89b8f8e61490bb689969278/lib/atom-react.coffee)

**Comment by jnrepo** [comment]
downgrading to atom 1.21.2 worked, thanks @dead

**Comment by dklanac** [comment]
@dead Your local patch worked for me. @jnrepo was it easy to downgrade atom quickly?

**Comment by jnrepo** [comment]
@dklanac using a mac atm, and it was pretty easy. Just had to delete the Atom package and then redownload the previous version and install that one.

[previous version link](https://github.com/atom/atom/releases/tag/v1.21.2)

**Comment by AdrianDroid** [comment]
+1000 here

**Comment by Em-Ant** [comment]
@dead patch works !!! Thanks !

**Comment by grohsfabian** [comment]
@dead Thanks for the patch :) 👍

**Comment by MV88** [comment]
if he's dead how can he write here?? ;)

btw it worked downgrading to atom 1.21.2

**Comment by infolock** [comment]
making the change to the file Gustavo seemed to work for me.   thanks

**Comment by chetanvj** [comment]
@dead There is no such .atom/packages/react/lib/atom-react.coffee file on my system. I'm using Windows 10, and all I see under c:\....\user\AppData\Local\atom\packages folder is SquirrelTemp folder, two nupkg files, a .betald file and RELEASES file.

**Comment by chetanvj** [comment]
@dead That worked for me, thanks!

**Comment by doppeldenk** [comment]
@dead Local patch worked, thanks!

**Comment by mindtonic** [comment]
+1

**Comment by malaymatwankar** [comment]
@dead replacing file worked grt thanks :smiley: :tada:

**Comment by sophiewikstrom** [comment]
@dead Thanks, it worked for me too! :)

**Comment by orktes** [comment]
0.17.0 release published with the patch from @dead . Kudos!
