### ISSUE TITLE
Uncaught TypeError: this.getRegexForProperty is not a function

### ISSUE THREAD

**Issue by midgethoen** [orktes/atom-react#255]
[Enter steps to reproduce:]
* type any char

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.16.0

### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:371:32)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3706:38)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:494:27)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1201:35
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1213:25)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:617:27)
    at /Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:676:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:55 refactor:done (input.hidden-input)
     -1:55 docblockr:parse-enter (input.hidden-input)
     -1:55 editor:newline (input.hidden-input)
     -1:54.8.0 refactor:done (input.hidden-input)
     -1:54.8.0 docblockr:parse-enter (input.hidden-input)
     -1:54.8.0 editor:newline (input.hidden-input)
     -1:54.6.0 refactor:done (input.hidden-input)
     -1:54.6.0 docblockr:parse-enter (input.hidden-input)
     -1:54.6.0 editor:newline (input.hidden-input)
     -1:54.4.0 refactor:done (input.hidden-input)
     -1:54.4.0 docblockr:parse-enter (input.hidden-input)
     -1:54.4.0 editor:newline (input.hidden-input)
     -1:54.2.0 refactor:done (input.hidden-input)
     -1:54.2.0 docblockr:parse-enter (input.hidden-input)
     -1:54.2.0 editor:newline (input.hidden-input)
     -1:21.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-ide-ui 0.5.4 
atom-import-sort 3.3.0 
atom-jade 0.3.0 
atom-runner 2.7.1 
atom-webbrowser 2.1.4 
atom-wordpress 0.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.13.2 
docker 0.7.0 
emmet 2.4.3 
es6-javascript 1.0.0 
gist 1.0.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
github-notifications 0.1.2 
http-status-codes 2.0.2 
ide-typescript 0.7.0 
intentions 1.1.5 
js-refactor 0.7.5 
json-schema 0.1.15 
language-cjsx 0.3.0 
language-docker 1.1.8 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-plantuml 0.2.0 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-php 1.3.2 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.10 
linter-ui-touchbar 0.2.1 
merge-conflicts 1.4.5 
node-debugger 1.10.1 
npm-install 4.0.4 
pipe 0.4.0 
plantuml-viewer 0.7.2 
react 0.16.0 
react-snippets 0.8.0 
refactor 0.11.5 
run-command 0.5.0 
sort-lines 0.18.0 
split-diff 1.4.3 
sync-settings 0.8.3 
tabularize 0.2.5 
termination 0.5.1 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
touchbar-registry 0.3.2 
vim-mode-plus 1.16.0 
webbox-color 0.5.9 
```

**Comment by midgethoen** [comment]
with all 3dparty packages: disabled

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.16.0


### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:371:32)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3706:38)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:494:27)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1201:35
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1213:25)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:617:27)
    at /Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:676:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:06.8.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-ide-ui 0.5.4 
atom-import-sort 3.3.0 
atom-jade 0.3.0 
atom-runner 2.7.1 
atom-webbrowser 2.1.4 
atom-wordpress 0.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.13.2 
docker 0.7.0 
emmet 2.4.3 
es6-javascript 1.0.0 
gist 1.0.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
github-notifications 0.1.2 
http-status-codes 2.0.2 
ide-typescript 0.7.0 
intentions 1.1.5 
js-refactor 0.7.5 
json-schema 0.1.15 
language-cjsx 0.3.0 
language-docker 1.1.8 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-plantuml 0.2.0 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-php 1.3.2 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.10 
linter-ui-touchbar 0.2.1 
merge-conflicts 1.4.5 
node-debugger 1.10.1 
npm-install 4.0.4 
pipe 0.4.0 
plantuml-viewer 0.7.2 
react 0.16.0 
react-snippets 0.8.0 
refactor 0.11.5 
run-command 0.5.0 
sort-lines 0.18.0 
split-diff 1.4.3 
sync-settings 0.8.3 
tabularize 0.2.5 
termination 0.5.1 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
touchbar-registry 0.3.2 
vim-mode-plus 1.16.0 
webbox-color 0.5.9 
```

**Comment by midgethoen** [comment]
With all non-core packages disabled (it still shows them in the error report, even after complete restart 🤔 )

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.2 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.1
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.16.0


### Stack Trace

Uncaught TypeError: this.getRegexForProperty is not a function

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:959

TypeError: this.getRegexForProperty is not a function
    at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/packages/react/lib/atom-react.coffee:79:38)
    at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:371:32)
    at TextEditor.module.exports.TextEditor.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:3706:38)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:494:27)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1201:35
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1213:25)
    at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditor.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:617:27)
    at /Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:677:40
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:952:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at HTMLElement.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/register-default-commands.js:676:28)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:381:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:03.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-ide-ui 0.5.4 
atom-import-sort 3.3.0 
atom-jade 0.3.0 
atom-runner 2.7.1 
atom-webbrowser 2.1.4 
atom-wordpress 0.3.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
change-case 0.6.5 
docblockr 0.13.2 
docker 0.7.0 
emmet 2.4.3 
es6-javascript 1.0.0 
gist 1.0.0 
git-control 0.9.0 
git-log 0.4.1 
git-plus 7.9.3 
github-notifications 0.1.2 
http-status-codes 2.0.2 
ide-typescript 0.7.0 
intentions 1.1.5 
js-refactor 0.7.5 
json-schema 0.1.15 
language-cjsx 0.3.0 
language-docker 1.1.8 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-plantuml 0.2.0 
linter 2.2.0 
linter-coffeelint 1.2.1 
linter-docker 0.2.1 
linter-eslint 8.4.0 
linter-js-yaml 1.2.8 
linter-jsonlint 1.3.0 
linter-lua 1.0.4 
linter-php 1.3.2 
linter-pycodestyle 2.0.2 
linter-ui-default 1.6.10 
linter-ui-touchbar 0.2.1 
merge-conflicts 1.4.5 
node-debugger 1.10.1 
npm-install 4.0.4 
pipe 0.4.0 
plantuml-viewer 0.7.2 
react 0.16.0 
react-snippets 0.8.0 
refactor 0.11.5 
run-command 0.5.0 
sort-lines 0.18.0 
split-diff 1.4.3 
sync-settings 0.8.3 
tabularize 0.2.5 
termination 0.5.1 
toggle-quotes 1.0.1 
tool-bar 1.1.0 
touchbar-registry 0.3.2 
vim-mode-plus 1.16.0 
webbox-color 0.5.9 
```

**Comment by midgethoen** [comment]
also same for error for 0.17.0

**Comment by midgethoen** [comment]
sry for dumping info like this. 

I currently unable to type any character in a js-file without getting the error.
I'm trying to figure it out, but I have no clue atm.

Any tips would be appreciated

**Comment by midgethoen** [comment]
the problem disappeared as sudden as it appeared 🤔 

I havent done anything special except for: 
 * restarting atom
 * uninstalling/installing the package
 * downgrading/upgrading the package

I also tried debugging the exception. which lead me to notice that the the `@tokenizedBuffer` property was set to be a TokenizedBuffer instance indeed but it had no `getRegexForProperty` method. 

I will close this as its not a problem for me and I can't even reproduce it anymore...
