### ISSUE TITLE
Failed to activate the react package

### ISSUE THREAD

**Issue by Toyrone** [orktes/atom-react#256]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.16.2

### Stack Trace

Failed to activate the react package

```
At Cannot read property 'jsxPatch' of undefined

TypeError: Cannot read property 'jsxPatch' of undefined
    at AtomReact.patchEditorLangModeAutoDecreaseIndentForBufferRow (/packages/react/lib/atom-react.coffee:41:17)
    at AtomReact.patchEditorLangMode (/packages/react/lib/atom-react.coffee:107:73)
    at AtomReact.processEditor (/packages/react/lib/atom-react.coffee:308:6)
    at Workspace.observeTextEditors (~/AppData/Local/atom/app-1.22.1/resources/app/src/workspace.js:725:15)
    at AtomReact.activate (/packages/react/lib/atom-react.coffee:330:46)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:253:25)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:690:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:665:36)
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:367:24)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:663:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.22.1/resources/app/src/package-manager.js:646:50)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/src/atom-environment.js:854:36
```

### Commands

```
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
atom-live-server 2.2.0 
emmet 2.4.3 
preview 0.17.0 
react 0.16.2 
teletype 0.2.3 
```

**Comment by jipiboily** [comment]
I had the same issue, looked at the README and saw there is a new version that fixes something for Atom 1.22....which fixed that for me. It looks like this was fixed 20 days ago. You just need to update the plugin :)

**Comment by danqing** [comment]
Seems it's breaking again for 1.24b1, latest version of the plugin.

**Comment by dougbacelar** [comment]
Worked for me when I upgraded the `react package` from **0.16.2** to **0.17.0**

I am using:
**Atom**: 1.22.1 x64
**OS**: Microsoft Windows 10

**Comment by jerrylow** [comment]
I keep trying to update but there seems to be this issue where it keeps asking to update. The issue persists eventhough I'm on 0.17.0.

![screen shot 2018-01-04 at 6 06 56 pm](https://user-images.githubusercontent.com/984430/34592603-330da84e-f17a-11e7-8af0-b3bfdb837bb1.png)

I've also tried uninstalling and re-installing.

**Comment by RaGreen** [comment]
Seems fixed finally in 0.18.0 :)

**Comment by kolosy** [comment]
Still present for me on 1.25

**Comment by Download** [comment]
Here now because I just did a fresh install of Atom and on first opening I hit this issue... I'll try updating.
