### ISSUE TITLE
Uncaught TypeError: this.tokenizedBuffer.regexForPattern is not a function

### ISSUE THREAD

**Issue by XBT1** [orktes/atom-react#260]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.17.0

### Stack Trace

Uncaught TypeError: this.tokenizedBuffer.regexForPattern is not a function

```
At /private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:899

TypeError: this.tokenizedBuffer.regexForPattern is not a function
    at TextEditor.editor.autoDecreaseIndentForBufferRow (/packages/react/lib/atom-react.coffee:51:54)
    at Selection.module.exports.Selection.insertText (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/selection.js:499:27)
    at /private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1201:35
    at /private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2621:24)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/private/var/folders/cm/_qgm4g894fd5jj3mldrhr79w0000gn/T/AppTranslocation/EE54266B-FF38-4922-B5A8-654BD3CFD64D/d/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:1631:28)
```

### Commands

```
     -0:58.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -0:33.8.0 core:close (input.hidden-input)
     -0:31.9.0 core:undo (input.hidden-input)
     -0:31 core:close (input.hidden-input)
     -0:26.6.0 tree-view:move (span.name.icon.jsx-icon.medium-blue)
  2x -0:25.7.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:25.1.0 core:backspace (input.hidden-input)
     -0:24.9.0 core:confirm (input.hidden-input)
     -0:22.1.0 editor:delete-to-beginning-of-line (input.hidden-input)
     -0:20.3.0 grammar-selector:show (atom-text-editor.editor.enable-atom-ide-find-references.is-focused)
     -0:18.4.0 core:move-down (input.hidden-input)
     -0:18.1.0 core:confirm (input.hidden-input)
     -0:16 core:close (input.hidden-input)
     -0:13.9.0 tree-view:move (li.file.entry.list-item.status-added.selected)
     -0:13.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:12.8.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
autocomplete-paths 2.12.1 
autoprefixer 3.7.1 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.15 
git-plus 7.10.0 
git-time-machine 1.5.9 
Hydrogen 2.2.0 
hyperclick 0.0.0 
ide-typescript 0.7.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
js-hyperclick 1.12.2 
language-ejs 0.4.0 
language-stylus 0.2.0 
language-vue 0.23.1 
linter 2.2.0 
linter-eslint 8.4.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.6.10 
minimap 4.29.7 
open-in-browser 0.5.2 
pigments 0.40.2 
pristine-ui 1.1.11 
react 0.17.0 
react-es6-snippets 0.3.0 
sort-lines 0.18.0 
stylus-autocompile 0.6.1 
todo-show 2.1.0 
tree-view-git-status 1.4.0 
vue-hyperclick 0.2.0 
```

**Comment by ElishebaW** [comment]
I just clicked within my test.js file

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [react](https://github.com/orktes/atom-react) package 0.17.0


### Stack Trace

Uncaught TypeError: this.tokenizedBuffer.regexForPattern is not a function

```
At /private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:854

TypeError: this.tokenizedBuffer.regexForPattern is not a function
    at TextEditor.editor.autoDecreaseIndentForBufferRow (/packages/react/lib/atom-react.coffee:51:54)
    at Selection.module.exports.Selection.insertText (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/selection.js:499:1)
    at /private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1127:1
    at /private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1166:1
    at TextBuffer.module.exports.TextBuffer.transact (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:849:1)
    at TextEditor.module.exports.TextEditor.transact (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1599:1)
    at /private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1160:1
    at TextEditor.module.exports.TextEditor.mergeSelections (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:2573:1)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:2539:1)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1158:1)
    at TextEditor.module.exports.TextEditor.insertText (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor.js:1124:1)
    at TextEditor.object.(anonymous function) [as insertText] (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:1)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor-component.js:480:1)
    at HTMLDivElement.<anonymous> (/private/var/folders/v6/g5hlc6j17971ydt622wk6p600000gn/T/AppTranslocation/AF7BC79B-0C86-4E81-BD7B-C79B933E444D/d/Atom.app/Contents/Resources/app/src/text-editor-component.js:3:1)
```

### Commands

```
     -1:50.9.0 platformio-ide-terminal:new (input.hidden-input)
  2x -1:02.3.0 editor:newline (input.hidden-input)
     -0:48.4.0 core:save (input.hidden-input)
  3x -0:47.1.0 editor:newline (input.hidden-input)
```

### Non-Core Packages

```
browser-plus 0.0.98 
platformio-ide-terminal 2.6.0 
react 0.17.0 
terminal-plus 0.14.5 
```

**Comment by ElishebaW** [comment]
@XBT1 I'm sure you already did this, but I just removed the package for now so I could get back to work. 


1. Go to atom preferences 
![screen shot 2017-12-28 at 1 01 57 pm](https://user-images.githubusercontent.com/20779752/34419020-786f1bbc-ebcf-11e7-8bbc-134feb45e91c.png)

2. Click Packages in prefrences
![screen shot 2017-12-28 at 1 02 11 pm](https://user-images.githubusercontent.com/20779752/34419022-819c6a28-ebcf-11e7-8073-60fd80002563.png)


3. Search for react
![screen shot 2017-12-28 at 1 02 21 pm](https://user-images.githubusercontent.com/20779752/34419027-891dac4e-ebcf-11e7-8f47-7aa8ca194c1e.png)

4. Click uninstall

**Comment by XBT1** [comment]
@ElishebaW hahahahahaha

**Comment by antongorodezkiy** [comment]
Oh, wow - I worked on the my current project many days before, but just right now got this issue when try to type any symbol.

**Comment by petermason** [comment]
same issue. uninstalled and reverted to previous version: apm install react@0.16.3

**Comment by mr-kenhoff** [comment]
I have the same issue. Even after reverting to 0.16.3.

**Comment by imdzeeshan** [comment]
I too had this issue. Updated to atom 1.23.3 resolved that.
