### ISSUE TITLE
apm install react@0.17.0

### ISSUE THREAD

**Issue by Greenboigz** [orktes/atom-react#263]
I am trying to install react on atom and am having this issue.

Installing react@0.17.0 to C:\Users\{User}\.atom\packages failed

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit  git+https://github.com/millermedeiros/rocambole.git#1bd5044df1d6c888a1bd1b511158fb34b011e9aa resetting remote C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:206:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:877:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\{User}\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: Cloning into bare repository 'C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85'...
npm ERR! git clone --template=C:\Users\{User}\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85: fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Users\\{User}\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\{User}\\AppData\\Local\\atom\\app-1.23.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\{User}\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\{User}\\.atom\\.apmrc" "install" "C:\\Users\\{User}\\AppData\\Local\\Temp\\d-11804-8252-zht1qc.7k4qkyy14i\\package.tgz" "--runtime=electron" "--target=1.6.15" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\{User}\.atom\.apm\_git-remotes\_templates --mirror https://github.com/millermedeiros/rocambole.git C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85
npm ERR! Cloning into bare repository 'C:\Users\{User}\.atom\.apm\_git-remotes\git-https-github-com-millermedeiros-rocambole-git-1bd5044df1d6c888a1bd1b511158fb34b011e9aa-af4fdf85'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\{User}\AppData\Local\Temp\apm-install-dir-11804-8252-16xncxm.0ttke29\npm-debug.log

**Comment by george82928** [comment]
Got the same issue here. Windows 10
