### ISSUE TITLE
Uncaught TypeError: this.tokenizedBuffer.regexForPattern is not a function

### ISSUE THREAD

**Issue by adewaguru** [orktes/atom-react#267]
TypeError: this.tokenizedBuffer.regexForPattern is not a function
    at TextEditor.editor.autoDecreaseIndentForBufferRow (/home/asanga/.atom/packages/react/lib/atom-react.coffee:51:54)
    at Selection.module.exports.Selection.insertText (/usr/share/atom/resources/app/src/selection.js:499:27)
    at /usr/share/atom/resources/app/src/text-editor.js:1201:35
    at /usr/share/atom/resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:894:24)
    at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app/src/text-editor.js:1673:32)
    at /usr/share/atom/resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/usr/share/atom/resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/usr/share/atom/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/usr/share/atom/resources/app/src/text-editor-component.js:1651:28)

**Comment by Dajust** [comment]
is there a way to go back to the past working version pending when this issue is resolved?

**Comment by Dajust** [comment]
I just upgraded my atom to v-1.24.0 and it seems to be fine for now :sweat_smile:

**Comment by adcar** [comment]
`CoffeeScript (JSX)` Seems to work but `JavaScript (JSX)` doesn't. Also, this error only happens on MacOS for me.

**Comment by batiste** [comment]
Same here... tiring

**Comment by adityarar** [comment]
How to revert to previous version to avoid this error

**Comment by Contactician** [comment]
Started getting this error today, updated Atom and that fixed it for about an hour but it just came back. It errors when I press any key, would love to know of any workarounds because this would be so nice to have.

**Comment by toddmetheny** [comment]
I'm having the same issue and am going to have to disable the package. Any word on when this will be addressed?

**Comment by ylvare** [comment]
Hi, I also have this issue. Would be nice with a fix. :)

**Comment by anisometropie** [comment]
I have this issue as well

**Comment by nklnsk** [comment]
Me too, Atom on Linux Mint.

**Comment by giampaolo44** [comment]
> I completely uninstalled Atom and reinstalled to the current version (1.26) and no longer get this error. Something in my original install seems to have been the problem, no longer an issue when the slate is wiped clean.

This solution worked, for me, thanks @Inventsable  :)
I was on 1.19.4-01 and by installing react I got the errors. By uninstalling and moving to the current one (1.34.0) it now works flawlessly.

**Comment by andela-mallan** [comment]
I tried updating atom and it kept failing to do so. I just decided it was much simpler to delete it and redownload it. It fixed this issue
