### ISSUE TITLE
Unable to edit a react file : TypeError: this.tokenizedBuffer.regexForPattern is not a function

### ISSUE THREAD

**Issue by JayashreeSrini** [orktes/atom-react#268]
TypeError: this.tokenizedBuffer.regexForPattern is not a function
    at TextEditor.editor.autoDecreaseIndentForBufferRow (/Users/a545305/.atom/packages/react/lib/atom-react.coffee:51:54)
    at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:499:27)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1201:35
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1240:34
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:953:24)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1673:32)
    at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1234:30
    at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2617:49)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:2583:41)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1232:25)
    at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1198:25)
    at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:1631:28)

Getting this kind of error... Kindly let us know how to resolve....

**Comment by srivenky12** [comment]
same prob happened for me,try to update atom and see
