### ISSUE TITLE
Uncaught TypeError: Cannot read property 'testSync' of undefined

### ISSUE THREAD

**Issue by fejlfri** [orktes/atom-react#30]
Simply restarting Atom solved the issue for me. Nevertheless.

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [react](https://github.com/orktes/atom-react) package, v0.9.8

### Stack Trace

Uncaught TypeError: Cannot read property 'testSync' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:124

TypeError: Cannot read property 'testSync' of undefined
  at LanguageMode.editor.languageMode.suggestedIndentForBufferRow (/Users/daniel/.atom/packages/react/lib/atom-react.coffee:65:47)
  at LanguageMode.module.exports.LanguageMode.autoIndentBufferRow (/Applications/Atom.app/Contents/Resources/app/src/language-mode.js:374:26)
  at TextEditor._results.push._this.(anonymous function) [as autoIndentBufferRow] (/Applications/Atom.app/Contents/Resources/app/node_modules/delegato/lib/delegator.js:67:61)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app/src/selection.js:478:21)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:773:31
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor.js:812:27
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:805:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:770:21)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.module.exports.TextEditor.insertNewline (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:789:19)
  at TextEditor.object.(anonymous function) [as insertNewline] (/Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.editor:newline (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:590:19)
  at /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:305:34
  at History.module.exports.History.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/history.js:115:18)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:687:27)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/src/text-editor.js:1181:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:08.9 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "react": {
    "jsxTagStartPattern": "(?x)((^|=|return)\\s*<([^!/?](?!. ?(</. ?>))))",
    "jsxComplexAttributePattern": "(?x)\\{ [^}\"']* $|\\( [^)\"']* $",
    "decreaseIndentForNextLinePattern": "(?x) />\\s*(,|;)?\\s*$ | ^\\s*\\S .*</[-_\\.A-Za-z0-9] >$"
  }
}
```

### Installed Packages

```coffee
# User
editorconfig, v0.3.0
linter, v0.10.1
linter-jshint, v0.1.0
linter-jsxhint, v0.1.0
react, v0.9.8

# Dev
No dev packages
```

/cc @atom/core

**Comment by orktes** [comment]
Hi! Did these problems appear after upgrading the plugin?

**Comment by fejlfri** [comment]
Hi orktes,

No. Been using v0.9.8 for a couple of days without experiencing any problems. The error occurred right after opening a project folder in Atom. It hasn't happened since.

**Comment by orktes** [comment]
Changed the way pattern config is done (less hacky). Hopefully this will fix this from happening in the future. Closing for now.
