### ISSUE TITLE
Atom 0.187.0 Throws an error every time I open it

### ISSUE THREAD

**Issue by AdamKyle** [orktes/atom-react#45]
The error is:

```js
Failed to load the atom-react-master package
Cannot find module 'jstransform/src/docblock'
Hide Stack Trace
Error: Cannot find module 'jstransform/src/docblock'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Users/Adam/Documents/Development-Tools/Atom 2.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/Adam/.atom/packages/atom-react-master/index.coffee:6:14)
    at Object.<anonymous> (/Users/Adam/.atom/packages/atom-react-master/index.coffee:34:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (/Users/Adam/Documents/Development-Tools/Atom 2.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

This happened right after I updated atom and after I updated packages that I use with atom

**Comment by orktes** [comment]
Hi! What version of atom-react are you using? Docblock detection code has
not been around for some time.

**Comment by AdamKyle** [comment]
it sais, 0.5.2 is currently installed. Whats funny is it always sais this. I always have to update it from this version. Uninstalling it crashes atom.

**Comment by orktes** [comment]
Have you tried reinstalling/removing it trough apm?
